server:
  port: 8000

spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    consul:
      host: consul.local
      port: 8500
      discovery:
        prefer-ip-address: true
    gateway:
      # discovery.locator:
      #   enabled: true
      #   lowerCaseServiceId: true
      routes:
        - id: student-service
          uri: lb://spring-consul-client-student-service
          predicates:
            - Path=/student-service/**
          filters:
            - RewritePath=/student-service/(?<path>.*), /$\{path}
        - id: school-service
          uri: lb://spring-consul-client-school-service
          predicates:
            - Path=/school-service/**
          filters:
            - RewritePath=/school-service/(?<path>.*), /$\{path}

# management:
#   endpoints:
#     web:
#       exposure:
#         include: "*"        
